"use client";
import Link from "next/link";
import { ArrowRight,Brain,ChartNoAxesCombined,Crosshair,Focus,Gamepad2,Timer,Waypoints } from "lucide-react";
import { Logo,ThemeToggle } from "@/components/theme-logo";
const skills=[[Timer,"Tempo de reação","Responder com precisão a estímulos sob tempo."],[Waypoints,"Tomada de decisão","Escolher caminhos com clareza sob pressão."],[Focus,"Foco e atenção","Sustentar a concentração e filtrar distrações."],[Brain,"Raciocínio rápido","Reconhecer padrões e resolver problemas com agilidade."]];
const games=["Aim Lab","KovaaK’s","Escape Simulator 2","osu!","Rhythia"];
export default function Home(){return <main className="overflow-hidden"><header className="sticky top-0 z-50 border-b border-[var(--line)] bg-[color:var(--bg)]/85 backdrop-blur-xl"><div className="container flex h-18 items-center justify-between"><Logo/><nav className="desktop flex gap-7 text-sm muted"><a href="#metodo">Como funciona</a><a href="#habilidades">Habilidades</a><a href="#jogos">Jogos</a><a href="#evidencias">Evidências</a></nav><div className="flex gap-2"><ThemeToggle/><Link className="btn btn-primary desktop" href="/login">Acessar plataforma <ArrowRight size={16}/></Link></div></div></header>
<section className="relative min-h-[86vh] flex items-center py-24"><div className="orb right-[-100px] top-10"/><div className="grid-noise absolute inset-0 opacity-30"/><div className="container relative grid gap-14 lg:grid-cols-[1.15fr_.85fr] items-center"><div><p className="eyebrow mb-6">Jogue com intenção. Evolua com clareza.</p><h1 className="title font-black">Seu jogo.<br/><span className="purple">Seu foco.</span><br/>Sua evolução.</h1><p className="muted mt-7 max-w-xl text-lg leading-relaxed">A FOCUS.GG transforma jogos de PC em ambientes de treino cognitivo orientado — com método, metas e acompanhamento consciente.</p><div className="mt-9 flex flex-wrap gap-3"><Link className="btn btn-primary" href="/login">Começar agora <ArrowRight size={18}/></Link><a className="btn surface" href="#metodo">Entender o método</a></div><p className="muted mt-5 text-xs">Projeto educacional • SENAC Nações Unidas</p></div><div className="surface card relative min-h-[410px] shadow-2xl shadow-purple-950/10"><div className="flex justify-between"><span className="pill">PAINEL DE EVOLUÇÃO</span><span className="eyebrow">+14,8%</span></div><div className="mt-12 flex items-end gap-2 h-32" aria-label="Gráfico demonstrativo de evolução">{[32,46,41,59,68,64,82,92].map((h,i)=><div key={i} className="flex-1 rounded-t-lg bg-[var(--purple)] opacity-[.35] last:opacity-100" style={{height:`${h}%`}}/>)}</div><div className="mt-10 grid grid-cols-2 gap-3"><div className="surface rounded-2xl p-4"><Crosshair className="purple"/><p className="mt-5 text-2xl font-black">82%</p><p className="muted text-sm">Precisão</p></div><div className="surface rounded-2xl p-4"><Timer className="purple"/><p className="mt-5 text-2xl font-black">318 ms</p><p className="muted text-sm">Tempo de resposta</p></div></div></div></div></section>
<section id="metodo" className="py-28"><div className="container"><p className="eyebrow">Método FOCUS</p><h2 className="section-title mt-4 max-w-3xl font-black">Do primeiro diagnóstico à evolução que você consegue enxergar.</h2><div className="mt-14 grid gap-4 md:grid-cols-4">{[["01","Faça o teste","Um diagnóstico inicial organiza seu ponto de partida."],["02","Conheça seu nível","Receba uma classificação: Iniciante, Intermediário ou Avançado."],["03","Treine com orientação","Siga instruções claras dentro de jogos que você já conhece."],["04","Registre e compare","Salve suas métricas e acompanhe mudanças ao longo do tempo."]].map(x=><article className="surface card" key={x[0]}><span className="purple font-black">{x[0]}</span><h3 className="mt-10 text-xl font-bold">{x[1]}</h3><p className="muted mt-3 leading-relaxed">{x[2]}</p></article>)}</div></div></section>
<section id="habilidades" className="py-28 bg-[var(--panel)]"><div className="container grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Habilidades</p><h2 className="section-title mt-4 font-black">Treine o que acontece entre o estímulo e a ação.</h2></div><div className="grid gap-4 sm:grid-cols-2">{skills.map(([Icon,t,d]:any)=><article className="surface card" key={t}><Icon className="purple"/><h3 className="mt-7 text-xl font-bold">{t}</h3><p className="muted mt-2">{d}</p></article>)}</div></div></section>
<section id="jogos" className="py-28"><div className="container"><div className="flex flex-wrap items-end justify-between gap-8"><div><p className="eyebrow">Ambientes de treino</p><h2 className="section-title mt-4 max-w-2xl font-black">Jogos existentes, usados com um novo propósito.</h2></div><Gamepad2 size={54} className="purple"/></div><div className="mt-14 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{games.map((g,i)=><div className="surface card min-h-40 flex flex-col justify-between" key={g}><span className="muted text-sm">0{i+1}</span><strong className="text-lg">{g}</strong></div>)}</div><p className="muted mt-6 text-xs">As marcas e jogos citados pertencem aos seus respectivos titulares. A FOCUS.GG é um projeto educacional independente e não possui afiliação oficial com eles.</p></div></section>
<section id="evidencias" className="py-24"><div className="container surface card !p-8 md:!p-14 grid gap-8 md:grid-cols-[1fr_auto] items-center"><div><p className="eyebrow">Uso consciente</p><h2 className="section-title mt-4 font-black">Mais intenção, não mais horas.</h2><p className="muted mt-5 max-w-2xl leading-relaxed">A proposta não substitui acompanhamento profissional nem promete resultados clínicos. Ela organiza práticas, pausas e observação de desempenho com base em fontes que serão publicadas pela equipe do projeto.</p></div><ChartNoAxesCombined size={72} className="purple"/></div></section>
<section className="py-28"><div className="container text-center"><p className="eyebrow">Pronto para começar?</p><h2 className="section-title mt-5 font-black">Transforme cada sessão em um treino com propósito.</h2><Link className="btn btn-primary mt-9" href="/login">Acessar a plataforma <ArrowRight size={18}/></Link></div></section><footer className="border-t border-[var(--line)] py-10"><div className="container flex flex-wrap justify-between gap-4"><Logo/><p className="muted text-sm">Projeto educacional • SENAC Nações Unidas</p></div></footer></main>}
