"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, BarChart3, BookOpen, ChevronRight, Home, LogOut, Plus, Save, Settings, Target, User, X } from "lucide-react";
import { Logo, ThemeToggle } from "@/components/theme-logo";
import { createSupabaseBrowserClient, isSupabaseConfigured } from "@/lib/supabase/client";

type Level="Iniciante"|"Intermediário"|"Avançado";
type Training={id:string;game:string;title:string;level:Level;skill:string;time:string;metric:string;instructions:string[]};
type Result={id:string;trainingId:string;title:string;game:string;metric:string;value:number;date:string};
const demoTrainings:Training[]=[
 {id:"demo-aim",game:"Aim Lab",title:"Gridshot — controle e ritmo",level:"Iniciante",skill:"Tempo de reação",time:"12 min",metric:"Precisão",instructions:["Faça um aquecimento de 2 minutos.","Complete três séries de Gridshot.","Descanse 60 segundos entre séries.","Registre a precisão da última série."]},
 {id:"demo-osu",game:"osu!",title:"Leitura visual consistente",level:"Intermediário",skill:"Foco e atenção",time:"15 min",metric:"Accuracy",instructions:["Escolha um mapa conhecido de dificuldade moderada.","Mantenha postura confortável e volume seguro.","Complete três tentativas com pausa curta.","Registre a accuracy da tentativa final."]},
 {id:"demo-kov",game:"KovaaK’s",title:"Target switching progressivo",level:"Intermediário",skill:"Tomada de decisão",time:"18 min",metric:"Score",instructions:["Abra o cenário Target Switching.","Priorize precisão antes de velocidade.","Complete quatro séries curtas.","Registre o score da melhor série."]},
 {id:"demo-escape",game:"Escape Simulator 2",title:"Sala sob restrição de tempo",level:"Intermediário",skill:"Raciocínio rápido",time:"25 min",metric:"Tempo",instructions:["Escolha uma sala ainda não memorizada.","Defina um limite de 25 minutos.","Verbalize prioridades antes de agir.","Registre o tempo de conclusão em segundos."]},
 {id:"demo-rhythm",game:"Rhythia",title:"Padrões e antecipação avançada",level:"Avançado",skill:"Foco e atenção",time:"20 min",metric:"Precisão",instructions:["Selecione um padrão desafiador, mas executável.","Faça uma tentativa de reconhecimento.","Complete três tentativas válidas.","Registre a precisão da melhor tentativa."]},
];
const demoResults:Result[]=[
 {id:"r1",trainingId:"demo-aim",title:"Gridshot — controle e ritmo",game:"Aim Lab",metric:"Precisão",value:78,date:"2026-07-20"},
 {id:"r2",trainingId:"demo-aim",title:"Gridshot — controle e ritmo",game:"Aim Lab",metric:"Precisão",value:82,date:"2026-08-02"},
 {id:"r3",trainingId:"demo-kov",title:"Target switching progressivo",game:"KovaaK’s",metric:"Score",value:84250,date:"2026-07-30"},
];
const dbToLevel=(value?:string|null):Level=>value==="beginner"?"Iniciante":value==="advanced"?"Avançado":"Intermediário";

export default function Platform(){
 const router=useRouter(); const [view,setView]=useState<"dashboard"|"treinos"|"resultados"|"perfil">("dashboard");
 const [loading,setLoading]=useState(true); const [showAll,setShowAll]=useState(false); const [profile,setProfile]=useState({username:"Theo",level:"Intermediário" as Level,avatarPath:""}); const [email,setEmail]=useState("demo@focus.gg");
 const [trainings,setTrainings]=useState<Training[]>(demoTrainings); const [results,setResults]=useState<Result[]>(demoResults); const [selected,setSelected]=useState<Training|null>(null); const [resultOpen,setResultOpen]=useState(false); const [notice,setNotice]=useState("");
 useEffect(()=>{(async()=>{if(!isSupabaseConfigured){setLoading(false);return}const sb=createSupabaseBrowserClient()!;const {data:{user}}=await sb.auth.getUser();if(!user){router.replace("/login");return}setEmail(user.email??"");const [{data:p},{data:t},{data:r},{data:s}]=await Promise.all([sb.from("profiles").select("username,level,avatar_path").eq("id",user.id).maybeSingle(),sb.from("trainings").select("id,game,title,level,cognitive_skill,duration_minutes,instructions,training_metrics(label)").eq("is_active",true),sb.from("training_results").select("id,training_id,metrics,performed_at,trainings(title,game,training_metrics(label))").order("performed_at",{ascending:false}),sb.from("user_settings").select("show_other_levels").eq("user_id",user.id).maybeSingle()]);if(p){if(!p.level){router.replace("/teste");return}setProfile({username:p.username,level:dbToLevel(p.level),avatarPath:p.avatar_path??""})}if(t?.length)setTrainings(t.map((x:any)=>({id:x.id,game:x.game,title:x.title,level:dbToLevel(x.level),skill:x.cognitive_skill,time:`${x.duration_minutes} min`,metric:x.training_metrics?.[0]?.label??"Resultado",instructions:Array.isArray(x.instructions)?x.instructions:[]})));if(r)setResults(r.map((x:any)=>({id:x.id,trainingId:x.training_id,title:x.trainings?.title??"Treino",game:x.trainings?.game??"—",metric:x.trainings?.training_metrics?.[0]?.label??"Resultado",value:Number(x.metrics?.value??0),date:x.performed_at.slice(0,10)})));if(s)setShowAll(s.show_other_levels);setLoading(false)})()},[router]);
 const visible=useMemo(()=>showAll?trainings:trainings.filter(t=>t.level===profile.level),[showAll,trainings,profile.level]);
 const evolution=useMemo(()=>{for(const current of results){const previous=results.find(x=>x.trainingId===current.trainingId&&x.id!==current.id);if(previous?.value)return ((current.value-previous.value)/previous.value)*100}return 0},[results]);
 async function toggleLevels(value:boolean){setShowAll(value);if(isSupabaseConfigured){const sb=createSupabaseBrowserClient()!;const {data:{user}}=await sb.auth.getUser();if(user)await sb.from("user_settings").upsert({user_id:user.id,show_other_levels:value})}}
 async function saveResult(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const fd=new FormData(event.currentTarget);const value=Number(fd.get("value"));const date=String(fd.get("date"));if(!Number.isFinite(value))return;let item:Result={id:crypto.randomUUID(),trainingId:selected.id,title:selected.title,game:selected.game,metric:selected.metric,value,date};if(isSupabaseConfigured){const sb=createSupabaseBrowserClient()!;const {data:{user}}=await sb.auth.getUser();if(user){const {data,error}=await sb.from("training_results").insert({user_id:user.id,training_id:selected.id,metrics:{value},notes:String(fd.get("notes")??""),performed_at:new Date(`${date}T12:00:00`).toISOString()}).select("id").single();if(error){setNotice("Não foi possível salvar o resultado.");return}item={...item,id:data.id}}}setResults([item,...results]);setResultOpen(false);setView("resultados");setNotice("Resultado registrado com sucesso.")}
 async function saveProfile(event:FormEvent<HTMLFormElement>){event.preventDefault();const fd=new FormData(event.currentTarget);const username=String(fd.get("username"));const password=String(fd.get("password"));if(isSupabaseConfigured){const sb=createSupabaseBrowserClient()!;const {data:{user}}=await sb.auth.getUser();if(user){const {error}=await sb.from("profiles").update({username}).eq("id",user.id);if(error){setNotice(error.message);return}if(password){const {error:e}=await sb.auth.updateUser({password});if(e){setNotice(e.message);return}}}}setProfile({...profile,username});setNotice("Perfil atualizado.")}
 async function uploadAvatar(file?:File){if(!file||!isSupabaseConfigured)return;const sb=createSupabaseBrowserClient()!;const {data:{user}}=await sb.auth.getUser();if(!user)return;const ext=file.name.split(".").pop();const path=`${user.id}/avatar.${ext}`;const {error}=await sb.storage.from("avatars").upload(path,file,{upsert:true});if(error){setNotice(error.message);return}await sb.from("profiles").update({avatar_path:path}).eq("id",user.id);setProfile({...profile,avatarPath:path});setNotice("Foto atualizada.")}
 async function logout(){if(isSupabaseConfigured)await createSupabaseBrowserClient()!.auth.signOut();router.push("/login")}
 if(loading)return <main className="min-h-screen grid place-items-center"><div className="text-center"><Logo/><p className="muted mt-4">Preparando seu painel…</p></div></main>;
 const recommended=trainings.find(t=>t.level===profile.level)??trainings[0];
 return <main className="min-h-screen"><header className="border-b border-[var(--line)]"><div className="container h-18 flex items-center justify-between"><Link href="/"><Logo/></Link><div className="flex items-center gap-2"><ThemeToggle/><button onClick={()=>setView("perfil")} className="surface rounded-full h-10 w-10 grid place-items-center" aria-label="Perfil"><User size={17}/></button></div></div></header><div className="container grid lg:grid-cols-[210px_1fr] gap-10 py-8"><aside className="hidden lg:flex flex-col gap-1">{[[Home,"dashboard","Visão geral"],[BookOpen,"treinos","Treinos"],[BarChart3,"resultados","Resultados"],[Settings,"perfil","Perfil"]].map(([Icon,id,label]:any)=><button key={id} onClick={()=>setView(id)} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-left ${view===id?"bg-[var(--purple)] text-white":"muted"}`}><Icon size={18}/>{label}</button>)}<Link className="muted flex items-center gap-2 mt-12 px-4 text-sm" href="/"><ArrowLeft size={15}/> Voltar ao site</Link><button onClick={logout} className="muted flex items-center gap-2 px-4 py-3 text-sm"><LogOut size={15}/> Sair</button></aside><section>{notice&&<div className="surface rounded-xl p-3 mb-5 text-sm flex justify-between">{notice}<button onClick={()=>setNotice("")}><X size={16}/></button></div>}
 {view==="dashboard"&&<Dashboard profile={profile} results={results} trainings={trainings} evolution={evolution} recommended={recommended} goTrainings={()=>setView("treinos")} goResults={()=>setView("resultados")}/>} 
 {view==="treinos"&&<><p className="eyebrow">Catálogo</p><h1 className="section-title mt-3 font-black">Treinos orientados</h1><p className="muted mt-3 max-w-2xl">Escolha uma sessão, siga as etapas dentro do jogo e registre somente a métrica indicada.</p><label className="surface card !p-4 mt-8 flex items-center justify-between cursor-pointer"><span><strong>Mostrar treinos de outros níveis</strong><small className="muted block mt-1">Seu nível continua destacado como recomendado.</small></span><input type="checkbox" checked={showAll} onChange={e=>toggleLevels(e.target.checked)} className="h-5 w-5 accent-[var(--purple)]"/></label><div className="mt-5 grid gap-4 md:grid-cols-2">{visible.map(t=><article className="surface card" key={t.id}><div className="flex justify-between gap-3"><span className="pill">{t.game}</span>{t.level===profile.level&&<span className="pill !border-[var(--purple)] purple">Recomendado</span>}</div><Target className="purple mt-8"/><h2 className="mt-4 text-xl font-black">{t.title}</h2><p className="muted mt-2">{t.skill} • {t.time}</p>{selected?.id===t.id&&<ol className="muted mt-5 grid gap-2 list-decimal pl-5">{t.instructions.map(x=><li key={x}>{x}</li>)}</ol>}<div className="mt-6 pt-5 border-t border-[var(--line)] flex justify-between gap-3 text-sm"><span className="muted">Registrar: {t.metric}</span><div className="flex gap-3"><button onClick={()=>setSelected(selected?.id===t.id?null:t)} className="purple font-bold">{selected?.id===t.id?"Fechar":"Ver orientação"}</button><button onClick={()=>{setSelected(t);setResultOpen(true)}} className="purple font-bold">Registrar →</button></div></div></article>)}</div></>}
 {view==="resultados"&&<><p className="eyebrow">Acompanhamento</p><h1 className="section-title mt-3 font-black">Resultados e evolução</h1><div className="mt-8 grid gap-4 sm:grid-cols-2"><Metric label="Evolução comparável" value={`${evolution>=0?"+":""}${evolution.toFixed(1)}%`} note="último treino com duas medições"/><Metric label="Consistência" value={`${results.length} sessões`} note="total registrado"/></div><div className="surface card mt-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Histórico</h2><button onClick={()=>{setSelected(trainings[0]);setResultOpen(true)}} className="btn btn-primary !py-2"><Plus size={16}/> Registrar</button></div><ResultTable results={results}/></div></>}
 {view==="perfil"&&<><p className="eyebrow">Sua conta</p><h1 className="section-title mt-3 font-black">Perfil</h1><form onSubmit={saveProfile} className="surface card mt-8 max-w-2xl"><div className="flex items-center gap-5"><div className="h-20 w-20 rounded-full bg-[var(--purple)] grid place-items-center text-white text-2xl font-black">{profile.username.slice(0,1).toUpperCase()}</div><div><h2 className="text-xl font-black">{profile.username}</h2><p className="muted">Nível {profile.level}</p><label className="purple text-sm font-bold mt-2 block cursor-pointer">Trocar foto<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>uploadAvatar(e.target.files?.[0])}/></label></div></div><div className="mt-8 grid gap-5"><Field name="username" label="Nome de usuário" defaultValue={profile.username}/><Field name="email" label="E-mail" value={email} disabled readOnly/><Field name="password" label="Nova senha (opcional)" type="password" placeholder="mínimo de 8 caracteres" minLength={8}/><button className="btn btn-primary justify-self-start"><Save size={16}/> Salvar alterações</button></div></form></>}
 </section></div>{resultOpen&&selected&&<ResultModal selected={selected} trainings={trainings} setSelected={setSelected} close={()=>setResultOpen(false)} save={saveResult}/>}<nav className="lg:hidden fixed bottom-3 left-3 right-3 surface rounded-2xl p-2 flex justify-around z-40">{[[Home,"dashboard"],[BookOpen,"treinos"],[BarChart3,"resultados"],[User,"perfil"]].map(([Icon,id]:any)=><button key={id} onClick={()=>setView(id)} className={view===id?"purple p-2":"muted p-2"}><Icon/></button>)}</nav></main>
}
function Dashboard({profile,results,trainings,evolution,recommended,goTrainings,goResults}:{profile:{username:string;level:Level};results:Result[];trainings:Training[];evolution:number;recommended?:Training;goTrainings:()=>void;goResults:()=>void}){return <><div className="flex flex-wrap justify-between gap-6"><div><p className="eyebrow">Painel pessoal</p><h1 className="section-title mt-3 font-black">Olá, {profile.username}.</h1><p className="muted mt-2">Seu próximo passo já está preparado.</p></div><span className="pill self-start">Nível • {profile.level}</span></div><div className="mt-9 grid gap-4 sm:grid-cols-3"><Metric label="Evolução recente" value={`${evolution>=0?"+":""}${evolution.toFixed(1)}%`} note="entre resultados comparáveis"/><Metric label="Sessões concluídas" value={String(results.length)} note="resultados registrados"/><Metric label="Treinos recomendados" value={String(trainings.filter(t=>t.level===profile.level).length)} note={`para nível ${profile.level}`}/></div>{recommended&&<article className="surface card mt-5"><span className="eyebrow">Recomendado para você</span><h2 className="mt-4 text-2xl font-black">{recommended.title}</h2><p className="muted mt-2">{recommended.game} • {recommended.skill} • {recommended.time}</p><button onClick={goTrainings} className="btn btn-primary mt-6">Ver orientação <ChevronRight size={17}/></button></article>}<div className="mt-10 flex justify-between"><h2 className="text-xl font-black">Atividade recente</h2><button onClick={goResults} className="purple text-sm font-bold">Ver resultados</button></div><ResultTable results={results.slice(0,3)}/></>}
function ResultModal({selected,trainings,setSelected,close,save}:{selected:Training;trainings:Training[];setSelected:(t:Training)=>void;close:()=>void;save:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="fixed inset-0 bg-black/60 z-50 grid place-items-center p-4"><form onSubmit={save} className="surface card w-full max-w-md"><div className="flex justify-between"><div><p className="eyebrow">Novo resultado</p><h2 className="mt-2 text-xl font-black">{selected.title}</h2></div><button type="button" onClick={close}><X/></button></div><div className="grid gap-5 mt-7"><label><span className="text-sm font-bold">Treino</span><select value={selected.id} onChange={e=>setSelected(trainings.find(t=>t.id===e.target.value)??selected)} className="surface mt-2 w-full rounded-xl px-4 py-3">{trainings.map(t=><option key={t.id} value={t.id}>{t.game} — {t.title}</option>)}</select></label><Field name="value" label={selected.metric} type="number" step="any" required/><Field name="date" label="Data" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/><label><span className="text-sm font-bold">Observação</span><textarea name="notes" maxLength={1000} className="surface mt-2 w-full rounded-xl px-4 py-3" rows={3}/></label><button className="btn btn-primary">Salvar resultado</button></div></form></div>}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <div className="surface card"><p className="muted text-sm">{label}</p><p className="mt-4 text-2xl font-black">{value}</p><p className="muted mt-1 text-xs">{note}</p></div>}
function ResultTable({results}:{results:Result[]}){return <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="muted"><tr><th className="py-3">Treino</th><th>Data</th><th>Métrica</th><th>Resultado</th></tr></thead><tbody>{results.map(r=><tr className="border-t border-[var(--line)]" key={r.id}><td className="py-4 pr-6">{r.title}</td><td className="pr-6">{new Intl.DateTimeFormat("pt-BR").format(new Date(`${r.date}T12:00:00`))}</td><td className="pr-6">{r.metric}</td><td>{r.value.toLocaleString("pt-BR")}</td></tr>)}</tbody></table>{results.length===0&&<p className="muted text-center py-10">Nenhum resultado registrado ainda.</p>}</div>}
function Field(props:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){const {label,...input}=props;return <label><span className="muted text-sm">{label}</span><input {...input} className="surface mt-2 w-full rounded-xl px-4 py-3 outline-none focus:border-[var(--purple)] disabled:opacity-60"/></label>}
