"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, CheckCircle2, Loader2 } from "lucide-react";
import { Logo } from "@/components/theme-logo";
import { createSupabaseBrowserClient, isSupabaseConfigured } from "@/lib/supabase/client";
const questions = [
    { key: "reaction", text: "Como você reage quando vários estímulos aparecem rapidamente?", answers: [["Preciso de tempo para organizar o que vejo", 1], ["Consigo reagir, mas perco precisão às vezes", 2], ["Reajo rápido e mantenho boa precisão", 3]] },
    { key: "focus", text: "Por quanto tempo você mantém a atenção em uma tarefa exigente?", answers: [["Menos de 10 minutos", 1], ["Entre 10 e 25 minutos", 2], ["Mais de 25 minutos", 3]] },
    { key: "pressure", text: "Como toma decisões quando o tempo é curto?", answers: [["Costumo travar ou escolher ao acaso", 1], ["Avalio as opções, mas posso hesitar", 2], ["Priorizo rapidamente e decido com clareza", 3]] },
    { key: "patterns", text: "Com que facilidade você reconhece padrões novos?", answers: [["Preciso de várias repetições", 1], ["Percebo depois de alguma prática", 2], ["Identifico padrões rapidamente", 3]] },
    { key: "consistency", text: "Como seu desempenho muda ao repetir uma atividade?", answers: [["Varia bastante entre tentativas", 1], ["Fica mais estável com aquecimento", 2], ["Permanece consistente desde o início", 3]] },
];
export default function Assessment() {
    const router = useRouter(); const [step, setStep] = useState(0); const [answers, setAnswers] = useState<Record<string, number>>({}); const [saving, setSaving] = useState(false); const q = questions[step]; const complete = step === questions.length; const score = Object.values(answers).reduce((a, b) => a + b, 0); const level = score <= 7 ? "Iniciante" : score <= 12 ? "Intermediário" : "Avançado";
    async function finish() { setSaving(true); if (isSupabaseConfigured) { const sb = createSupabaseBrowserClient()!; const { data: { user } } = await sb.auth.getUser(); if (user) { const dbLevel = level === "Iniciante" ? "beginner" : level === "Intermediário" ? "intermediate" : "advanced"; const { data: a } = await sb.from("assessments").insert({ user_id: user.id, score, level: dbLevel }).select("id").single(); if (a) await sb.from("assessment_answers").insert(Object.entries(answers).map(([question_key, score]) => ({ assessment_id: a.id, user_id: user.id, question_key, answer: { score }, score }))); await sb.from("profiles").update({ level: dbLevel }).eq("id", user.id); } } router.push("/plataforma"); }
    return <main className="min-h-screen"><header className="container h-20 flex items-center justify-between"><Logo /><span className="muted text-sm">Teste inicial</span></header><div className="container max-w-3xl py-10"><div className="h-1.5 bg-[var(--line)] rounded-full"><div className="h-full bg-[var(--purple)] rounded-full transition-all" style={{ width: `${Math.min(100, (step / questions.length) * 100)}%` }} /></div>{!complete ? <section className="mt-16"><p className="eyebrow">Pergunta {step + 1} de {questions.length}</p><h1 className="section-title mt-5 font-black">{q.text}</h1><div className="grid gap-3 mt-10">{q.answers.map(([label, value]) => <button key={String(label)} onClick={() => setAnswers({ ...answers, [q.key]: Number(value) })} className={`surface card text-left flex justify-between ${answers[q.key] === value ? "!border-[var(--purple)]" : ""}`}><span>{label}</span>{answers[q.key] === value && <CheckCircle2 className="purple" />}</button>)}</div><div className="mt-10 flex justify-between"><button disabled={step === 0} onClick={() => setStep(step - 1)} className="btn surface disabled:opacity-30"><ArrowLeft size={17} /> Voltar</button><button disabled={!answers[q.key]} onClick={() => setStep(step + 1)} className="btn btn-primary disabled:opacity-40">Continuar <ArrowRight size={17} /></button></div></section> : <section className="surface card !p-10 mt-16 text-center"><CheckCircle2 className="purple mx-auto" size={48} /><p className="eyebrow mt-7">Seu ponto de partida</p><h1 className="section-title mt-4 font-black">Nível {level}</h1><p className="muted mt-5 max-w-lg mx-auto">Esta classificação organiza suas primeiras recomendações. Ela não é um diagnóstico e pode ser revista conforme seus resultados.</p><button onClick={finish} disabled={saving} className="btn btn-primary mt-9">{saving ? <Loader2 className="animate-spin" /> : <>Ver meu painel <ArrowRight size={17} /></>}</button></section>}</div></main>
}
